Repository WTTJ/welcome-ui, pull requests merged in 2023-09, with the labels that each got.

#2219 Fix(slider): connect input and slider position, disabled input, values style
  packages/Slider/src/Range.tsx
  packages/Slider/src/index.tsx
  packages/Slider/tests/index.test.tsx
Labels: bug, approved

#2235 chore: upgrade node LTS
  .circleci/config.yml
  .tool-versions
Labels: approved

#2209 chore: allow and apply unicodeRange
  docs/pages/theming/customize.mdx
  packages/Core/src/utils/font.ts
Labels: approved

#2252 feat: remove listitem on tag for accessibility
  packages/Tag/src/index.tsx
Labels: approved

#2270 chore: add auto github release with changelog
  .circleci/config.yml
  .github/workflows/release.yml
Labels: approved

#2271 chore: upgrade github release action
  .github/workflows/release.yml
Labels: to-review

#2253 feat: add stroke on Tooltip
  packages/Core/src/theme/tooltips.ts
Labels: approved, design-review

#2276 feat: add @swc/jest
  jest.config.js
  package.json
  yarn.lock
Labels: approved

#2280 fix: remove useless alwaysVisible on dropdownMenu
  packages/DropdownMenu/src/index.tsx
Labels: approved

#2275 fix: release auto tag
  .github/workflows/release.yml
Labels: approved

#2281 ci: fix autochangelog
  .github/workflows/release.yml
Labels: approved

#2286 fix: zIndex on modal Header and Footer
  packages/Modal/src/styles.ts
Labels: approved

#2288 fix: drawer width on mobile
  packages/Drawer/src/styles.ts
Labels: to-review

#2290 fix: maxHeigth on modal body crash on mobile
  packages/Modal/src/styles.ts
Labels: approved

#2293 ci: fix auto release on tag publish
  .github/workflows/release.yml
Labels: approved

#2292 fix: swiper custom button background
  packages/Swiper/src/styles.ts
Labels: approved

#2291 fix: swiper reload if children changed
  packages/Swiper/src/index.tsx
Labels: approved

#2282 fix: glitch on Popover with an hover
  docs/pages/components/popover.mdx
  packages/Popover/package.json
  packages/Popover/src/Arrow.tsx
  packages/Popover/src/Content.tsx
  packages/Popover/src/Popover.tsx
  packages/Popover/src/PopoverHover.tsx
  packages/Popover/src/Trigger.tsx
  packages/Popover/src/index.tsx
  packages/Popover/src/styles.ts
  packages/Popover/src/usePopover.ts
  packages/Popover/tests/hover.test.tsx
Labels: approved
