Repository WTTJ/welcome-ui, pull requests merged in 2023-10, with the labels that each got.

#2312 fix: misaligned radio on RadioGroup
  packages/Radio/src/index.tsx
  packages/Radio/src/styles.ts
Labels: approved

#2329 feat: add X icon
  docs/components/IconsList/icons.js
  docs/constants.js
  docs/pages/components/dropdown-menu.mdx
  docs/pages/components/icons-font.mdx
  docs/pages/components/icons.mdx
  docs/pages/components/picker.mdx
  docs/pages/components/select.mdx
  icons/_assets/x.svg
  icons/src/X/content.json
  icons/src/X/index.tsx
  icons/src/index.d.ts
  icons/src/index.ts
  packages/IconFont/src/unicode.json
  scripts/tests.js
Labels: approved

#2332 chore: upgrade ariakit 3.0.4
  docs/pages/components/modal.mdx
  docs/pages/upgrade.mdx
  packages/Accordion/package.json
  packages/Button/package.json
  packages/Checkbox/package.json
  packages/Drawer/package.json
  packages/Drawer/src/index.tsx
  packages/DropdownMenu/package.json
  packages/Modal/package.json
  packages/Modal/src/index.tsx
  packages/Modal/src/styles.ts
  packages/Picker/package.json
  packages/Popover/package.json
  packages/Radio/package.json
  packages/RadioGroup/package.json
  packages/RadioTab/package.json
  packages/Tabs/package.json
  packages/Toggle/package.json
  packages/Tooltip/package.json
  yarn.lock
Labels: approved

#2338 fix(tooltip): always visible after hover
  packages/Tooltip/src/index.tsx
  packages/Tooltip/src/styles.ts
Labels: approved

#2330 fix: add missing dependencies
  .circleci/config.yml
  .depcheckrc.json
  .husky/pre-push
  docs/package.json
  package.json
  packages/Accordion/package.json
  packages/Alert/package.json
  packages/AspectRatio/package.json
  packages/Badge/package.json
  packages/Button/package.json
  packages/Copy/package.json
  packages/Core/package.json
  packages/DatePicker/package.json
  packages/DateTimePicker/package.json
  packages/DateTimePickerCommon/package.json
  packages/Emoji/package.json
  packages/EmojiPicker/package.json
  packages/Field/package.json
  packages/FileDrop/package.json
  packages/Files/package.json
  packages/Hint/package.json
  packages/IconFont/package.json
  packages/MarkdownEditor/package.json
  packages/Modal/package.json
  packages/Picker/package.json
  packages/RadioTab/package.json
  packages/Search/package.json
  packages/Select/package.json
  packages/Slider/package.json
  packages/Tag/package.json
  packages/Themes/WelcomeDark/package.json
  packages/TimePicker/package.json
  packages/Toast/package.json
  yarn.lock
Labels: approved

#2339 feat(tooltip): add gutter prop
  packages/Tooltip/src/index.tsx
Labels: approved

#2343 fix(vulnerabilities): @babel/traverse
  package.json
  yarn.lock
Labels: to-review

#2342 fix(modal): not visible while updating state on open
  packages/Modal/src/index.tsx
  packages/Modal/tests/index.test.tsx
Labels: approved

#2331 feat(panda): badge component
  package.json
  packages/Badge/package.json
  packages/Badge/src/index.tsx
  packages/Badge/src/panda.tsx
  packages/Badge/stories/index.stories.tsx
  packages/Core/src/index.ts
  packages/Core/src/panda/recipes/badge.ts
  packages/Core/src/panda/recipes/button.ts
  packages/Core/src/panda/recipes/index.ts
  types/styled.d.ts
  yarn.lock
Labels: approved, panda 🐼

#2351 feat(experimental): panda Text
  package.json
  packages/Core/src/panda/recipes/index.ts
  packages/Core/src/panda/recipes/text.ts
  packages/Core/src/panda/textStyles.ts
  packages/Core/src/panda/tokens/letterSpacings.ts
  packages/Core/src/panda/tokens/lineHeights.ts
  packages/Text/src/index.tsx
  packages/Text/src/panda.tsx
  packages/Text/stories/index.stories.tsx
  types/styled.d.ts
  yarn.lock
Labels: approved

#2352 feat: update drag and drop icon
  icons/_assets/drag_and_drop.svg
  icons/src/DragAndDrop/content.json
Labels: approved

#2353 fix: remove panda
  .circleci/config.yml
  .depcheckrc.json
  .eslintignore
  .ladle/components.tsx
  .ladle/style.css
  package.json
  packages/Badge/package.json
  packages/Badge/src/index.tsx
  packages/Badge/src/panda.tsx
  packages/Badge/stories/index.stories.tsx
  packages/Button/package.json
  packages/Button/src/index.tsx
  packages/Button/src/panda.tsx
  packages/Button/stories/index.stories.tsx
  packages/Core/package.json
  packages/Core/src/WuiProvider.tsx
  packages/Core/src/index.ts
  packages/Core/src/panda/breakpoints.ts
  packages/Core/src/panda/fonts.css
  packages/Core/src/panda/globalCss.ts
  packages/Core/src/panda/index.ts
  packages/Core/src/panda/recipes/badge.ts
  packages/Core/src/panda/recipes/button.ts
  packages/Core/src/panda/recipes/index.ts
  packages/Core/src/panda/recipes/shape.ts
  packages/Core/src/panda/recipes/text.ts
  packages/Core/src/panda/textStyles.ts
  packages/Core/src/panda/tokens/borders.ts
  packages/Core/src/panda/tokens/colors.ts
  packages/Core/src/panda/tokens/durations.ts
  packages/Core/src/panda/tokens/easings.ts
  packages/Core/src/panda/tokens/fontSizes.ts
  packages/Core/src/panda/tokens/fontWeights.ts
  packages/Core/src/panda/tokens/fonts.ts
  packages/Core/src/panda/tokens/index.ts
  packages/Core/src/panda/tokens/letterSpacings.ts
  packages/Core/src/panda/tokens/lineHeights.ts
  packages/Core/src/panda/tokens/radii.ts
  packages/Core/src/panda/tokens/shadows.ts
  packages/Core/src/panda/tokens/spacing.ts
  packages/Core/src/panda/utilities.ts
  packages/Core/src/utils/base.ts
  packages/Panda/.gitignore
  packages/Panda/package.json
  packages/Shape/package.json
  packages/Shape/src/index.tsx
  packages/Shape/src/panda.tsx
  packages/Shape/stories/index.stories.tsx
  packages/Text/src/index.tsx
  packages/Text/src/panda.tsx
  packages/Text/stories/index.stories.tsx
  packages/Themes/Welcome/package.json
  packages/Themes/Welcome/src/index.ts
  packages/Themes/Welcome/src/preset.ts
  panda.config.ts
  postcss.config.cjs
  types/styled.d.ts
  yarn.lock
Labels: approved
