Repository WTTJ/welcome-ui, pull requests merged in 2024-10, with the labels that each got.

#2543 chore: add border radius on components
  lerna.json
  packages/Core/package.json
  packages/Core/src/theme/accordions.ts
  packages/Core/src/theme/alerts.ts
  packages/Core/src/theme/buttons.ts
  packages/Core/src/theme/cards.ts
  packages/Core/src/theme/checkboxes.ts
  packages/Core/src/theme/core.ts
  packages/Core/src/theme/defaultFields.ts
  packages/Core/src/theme/dropdownMenu.ts
  packages/Core/src/theme/modals.ts
  packages/Core/src/theme/radii.ts
  packages/Core/src/theme/tags.ts
  packages/Core/src/theme/toasts.ts
  packages/DropdownMenu/package.json
  packages/EmojiPicker/package.json
  packages/EmojiPicker/src/styles.ts
  packages/Modal/package.json
  packages/Modal/src/Assets/AssetWithTitle.tsx
  packages/Themes/Dark/package.json
  packages/Themes/Welcome/package.json
  packages/Themes/WelcomeDark/package.json
  packages/Toast/docs/examples/overview.tsx
  packages/Toast/docs/examples/toast.tsx
  packages/Toast/package.json
  packages/Toast/src/styles.ts
  website/build-app/pages/foundations/theming/basics.mdx
Labels: approved

#2552 chore: update radii migration script
  scripts/upgrade-radii.js
Labels: to-review

#2567 fix(Tabs): update gap small size [WUI-19]
  packages/Core/src/theme/tabs.ts
  packages/Tabs/src/styles.ts
Labels: approved

#2561 [WUI-45] fix: avoid welcome-font cut letters
  packages/Text/src/styles.ts
Labels: approved

#2572 Chore(Select): use pointer cursor when hovering select options [WUI-50]
  packages/Select/docs/examples/creatable-custom.tsx
  packages/Select/src/styles.ts
Labels: changes-requested

#2581 chore: add website build deploy for version 5
  .circleci/config.yml
  website/public/robots.txt
Labels: approved

#2580 fix(Modal): border radius and overflow
  README.md
  lerna.json
  packages/Core/package.json
  packages/Core/src/theme/modals.ts
  packages/DropdownMenu/package.json
  packages/Modal/package.json
  packages/Themes/Dark/package.json
  packages/Themes/Welcome/package.json
  packages/Themes/WelcomeDark/package.json
Labels: approved
