Repository WTTJ/welcome-ui, pull requests merged in 2025-09, with the labels that each got.

#2806 Fix: use a contrast compliant color for texts
  lib/src/components/Breadcrumb/theme.ts
  lib/src/components/Link/theme.ts
  lib/src/components/Slider/Range.tsx
  lib/src/components/Slider/index.tsx
  lib/src/components/Slider/styles.ts
  lib/src/components/Tabs/theme.ts
  lib/src/theme/defaultFields.ts
Labels: approved

#2810 chore(yarn audit): fix vulnerabilities
  package.json
  website/package.json
  yarn.lock
Labels: approved

#2821 chore: update aliases config
  lib/tsconfig.json
  lib/vite.config.mjs
Labels: approved

#2826 Fix button documentation
  lib/src/components/Button/docs/examples/ai.tsx
  lib/src/components/Button/docs/examples/danger.tsx
  lib/src/components/Button/docs/examples/icons.tsx
  lib/src/components/Button/docs/examples/shapes.tsx
  lib/src/components/Button/docs/examples/variants.tsx
  lib/src/components/Button/docs/index.mdx
  lib/src/components/Button/docs/properties.json
  lib/src/old/components/WuiProvider/styles.ts
  website/app/global.css
  website/build-app/components/ThemeProvider/index.tsx
Labels: approved

#2818 [WUI-211] Chore: migrate button group
  lib/src/components/Button/button.module.scss
  lib/src/components/Button/docs/properties.json
  lib/src/components/Button/index.tsx
  lib/src/components/Button/types.ts
  lib/src/components/ButtonGroup/button-group.module.scss
  lib/src/components/ButtonGroup/docs/examples/overload.tsx
  lib/src/components/ButtonGroup/docs/examples/overview.tsx
  lib/src/components/ButtonGroup/docs/index.mdx
  lib/src/components/ButtonGroup/docs/properties.json
  lib/src/components/ButtonGroup/index.test.tsx
  lib/src/components/ButtonGroup/index.tsx
  lib/src/components/ButtonGroup/types.ts
  website/build-app/examples.js
Labels: approved

#2847 docs: fix exports of components in docs files
  lib/src/components/Button/docs/examples/ai.tsx
  lib/src/components/Button/docs/examples/danger.tsx
  lib/src/components/Button/docs/examples/disabled.tsx
  lib/src/components/Button/docs/examples/icons.tsx
  lib/src/components/Button/docs/examples/is-loading.tsx
  lib/src/components/Button/docs/examples/link.tsx
  lib/src/components/Button/docs/examples/overview.tsx
  lib/src/components/Button/docs/examples/shapes.tsx
  lib/src/components/Button/docs/examples/sizes.tsx
  lib/src/components/Button/docs/examples/tailwind-class-overrides.tsx
  lib/src/components/Button/docs/examples/variants.tsx
  lib/src/components/Icon/docs/examples/color.tsx
  lib/src/components/Icon/docs/examples/overview.tsx
  lib/src/components/Icon/docs/examples/sizes.tsx
  lib/src/components/Icon/docs/index.mdx
  lib/src/components/VariantIcon/docs/examples/overview.tsx
  lib/src/components/VariantIcon/docs/examples/sizes.tsx
  website/app/blog/page.tsx
  website/app/page.tsx
  website/build-app/components/Mdx/Div.tsx
Labels: approved

#2834 chore: migrate input text to tailwind
  lib/src/components/InputText/docs/examples/clearable.tsx
  lib/src/components/InputText/docs/examples/disabled.tsx
  lib/src/components/InputText/docs/examples/icon.tsx
  lib/src/components/InputText/docs/examples/overview.tsx
  lib/src/components/InputText/docs/examples/sizes.tsx
  lib/src/components/InputText/docs/examples/transparent.tsx
  lib/src/components/InputText/docs/examples/variants.tsx
  lib/src/components/InputText/docs/index.mdx
  lib/src/components/InputText/docs/properties.json
  lib/src/components/InputText/index.tsx
  lib/src/components/InputText/input-text.module.scss
  lib/src/components/InputText/tests/index.test.tsx
  lib/src/components/InputText/types.ts
  website/app/global.css
  website/build-app/examples.js
Labels: to-review

#2835 chore: migrate textarea to tailwind
  lib/src/components/Textarea/docs/examples/overview.tsx
  lib/src/components/Textarea/docs/examples/variants.tsx
  lib/src/components/Textarea/docs/index.mdx
  lib/src/components/Textarea/docs/properties.json
  lib/src/components/Textarea/index.tsx
  lib/src/components/Textarea/tests/index.test.tsx
  lib/src/components/Textarea/textarea.module.scss
  lib/src/components/Textarea/types.ts
  website/app/global.css
  website/build-app/examples.js
Labels: to-review

#2836 [WUI-213] Chore: add forwardRefWithAs to handle polymorphism
  lib/src/components/Button/docs/index.mdx
  lib/src/components/Button/docs/properties.json
  lib/src/components/Button/index.test.tsx
  lib/src/components/Button/index.tsx
  lib/src/components/Button/types.ts
  lib/src/components/ButtonGroup/index.test.tsx
  lib/src/components/ButtonGroup/index.tsx
  lib/src/utils/forwardRefWithAs.tsx
  lib/tests/index.tsx
Labels: approved

#2851 chore: migrate the Avatar component to be tailwind-compatible
  lib/src/components/Avatar/avatar.module.scss
  lib/src/components/Avatar/docs/examples/images.tsx
  lib/src/components/Avatar/docs/examples/overview.tsx
  lib/src/components/Avatar/docs/examples/sizes.tsx
  lib/src/components/Avatar/docs/examples/texts.tsx
  lib/src/components/Avatar/docs/index.mdx
  lib/src/components/Avatar/docs/properties.json
  lib/src/components/Avatar/index.tsx
  lib/src/components/Avatar/tests/index.test.tsx
  lib/src/components/Avatar/tests/utils.test.ts
  lib/src/components/Avatar/types.ts
  lib/src/components/Avatar/utils.ts
  website/build-app/examples.js
Labels: approved

#2861 Chore: migrate welcome loader to tailwind [WUI-163]
  lib/src/components/Avatar/tests/index.test.tsx
  lib/src/components/WelcomeLoader/docs/examples/overview.tsx
  lib/src/components/WelcomeLoader/docs/examples/resize.tsx
  lib/src/components/WelcomeLoader/docs/index.mdx
  lib/src/components/WelcomeLoader/docs/properties.json
  lib/src/components/WelcomeLoader/index.tsx
  lib/src/components/WelcomeLoader/loader.json
  website/build-app/examples.js
Labels: approved

#2860 chore: migrate Pagination
  lib/src/components/Pagination/docs/examples/custom-navigation.tsx
  lib/src/components/Pagination/docs/examples/overview.tsx
  lib/src/components/Pagination/docs/examples/range.tsx
  lib/src/components/Pagination/docs/index.mdx
  lib/src/components/Pagination/docs/properties.json
  lib/src/components/Pagination/index.tsx
  lib/src/components/Pagination/pagination.module.scss
  lib/src/components/Pagination/tests/index.test.tsx
  lib/src/components/Pagination/types.ts
  lib/src/components/Pagination/utils.ts
  lib/src/components/Toggle/docs/properties.json
  website/app/blog/page.tsx
  website/app/global.css
  website/build-app/components/Homepage/Components.tsx
  website/build-app/examples.js
Labels: approved

#2863 chore: migrate PasswordInput
  eslint-suppressions.json
  eslint.config.mjs
  lib/src/components/PasswordInput/ToggleButton.tsx
  lib/src/components/PasswordInput/docs/examples/overview.tsx
  lib/src/components/PasswordInput/docs/index.mdx
  lib/src/components/PasswordInput/docs/properties.json
  lib/src/components/PasswordInput/index.tsx
  lib/src/components/PasswordInput/tests/index.test.tsx
  website/build-app/examples.js
  website/build-app/utils/examples-page-exporter.ts
  website/loaders/generate-examples.js
Labels: to-review

#2862 chore: migrate AspectRatio
  lib/src/components/AspectRatio/aspect-ratio.module.scss
  lib/src/components/AspectRatio/docs/examples/map.tsx
  lib/src/components/AspectRatio/docs/examples/overview.tsx
  lib/src/components/AspectRatio/docs/examples/ratio.tsx
  lib/src/components/AspectRatio/docs/examples/video.tsx
  lib/src/components/AspectRatio/docs/index.mdx
  lib/src/components/AspectRatio/docs/properties.json
  lib/src/components/AspectRatio/index.tsx
  lib/src/components/AspectRatio/tests/index.test.tsx
  lib/src/components/AspectRatio/types.ts
  website/app/global.css
  website/build-app/examples.js
Labels: approved

#2870 chore: migrate Badge
  lib/src/components/Badge/badge.module.scss
  lib/src/components/Badge/docs/examples/disabled.tsx
  lib/src/components/Badge/docs/examples/number-abbreviation.tsx
  lib/src/components/Badge/docs/examples/overview.tsx
  lib/src/components/Badge/docs/examples/size.tsx
  lib/src/components/Badge/docs/examples/variant.tsx
  lib/src/components/Badge/docs/index.mdx
  lib/src/components/Badge/docs/properties.json
  lib/src/components/Badge/index.test.tsx
  lib/src/components/Badge/index.tsx
  lib/src/components/Badge/types.ts
  website/build-app/examples.js
Labels: approved

#2858 chore: migrate Tabs
  lib/src/components/Button/docs/properties.json
  lib/src/components/Tabs/components/ActiveBar/active-bar.module.scss
  lib/src/components/Tabs/components/ActiveBar/index.tsx
  lib/src/components/Tabs/components/TabList/index.tsx
  lib/src/components/Tabs/components/TabList/tab-list.module.scss
  lib/src/components/Tabs/components/TabPanel/index.tsx
  lib/src/components/Tabs/components/TabPanel/tab-panel.module.scss
  lib/src/components/Tabs/docs/examples/badge.tsx
  lib/src/components/Tabs/docs/examples/component.tsx
  lib/src/components/Tabs/docs/examples/no-border.tsx
  lib/src/components/Tabs/docs/examples/one.tsx
  lib/src/components/Tabs/docs/examples/overview.tsx
  lib/src/components/Tabs/docs/examples/sizes.tsx
  lib/src/components/Tabs/docs/examples/vertical.tsx
  lib/src/components/Tabs/docs/index.mdx
  lib/src/components/Tabs/docs/properties.json
  lib/src/components/Tabs/index.tsx
  lib/src/components/Tabs/tabs.module.scss
  lib/src/components/Tabs/tests/index.test.tsx
  lib/src/components/Tabs/types.ts
  lib/src/components/Tabs/utils.ts
  lib/src/components/Toggle/docs/properties.json
  lib/src/components/Toggle/index.test.tsx
  lib/src/components/Tooltip/docs/properties.json
  lib/src/utils/use-isomorphic-layout-effect.ts
  lib/src/utils/use-viewport.ts
  website/app/components/[id]/tabs.tsx
  website/app/foundations/[id]/tabs.tsx
  website/app/global.css
  website/build-app/examples.js
Labels: approved

#2844 chore(tag): migrate tag component to scss
  lib/src/components/Tag/docs/examples/clickable.tsx
  lib/src/components/Tag/docs/examples/on-remove.tsx
  lib/src/components/Tag/docs/examples/one-character.tsx
  lib/src/components/Tag/docs/examples/overview.tsx
  lib/src/components/Tag/docs/examples/sizes.tsx
  lib/src/components/Tag/docs/examples/variants.tsx
  lib/src/components/Tag/docs/index.mdx
  lib/src/components/Tag/docs/properties.json
  lib/src/components/Tag/index.test.tsx
  lib/src/components/Tag/index.tsx
  lib/src/components/Tag/tag.module.scss
  lib/src/components/Tag/types.ts
  lib/src/utils/index.ts
  website/app/global.css
  website/build-app/examples.js
Labels: approved

#2859 Chore: migrate select component to tailwind [WUI-171]
  lib/src/components/Select/docs/examples/allow-unselect-from-list.tsx
  lib/src/components/Select/docs/examples/clearable.tsx
  lib/src/components/Select/docs/examples/creatable-custom.tsx
  lib/src/components/Select/docs/examples/creatable.tsx
  lib/src/components/Select/docs/examples/formatting.tsx
  lib/src/components/Select/docs/examples/icon.tsx
  lib/src/components/Select/docs/examples/multiple-render.tsx
  lib/src/components/Select/docs/examples/multiple.tsx
  lib/src/components/Select/docs/examples/option-groups.tsx
  lib/src/components/Select/docs/examples/overview.tsx
  lib/src/components/Select/docs/examples/searchable.tsx
  lib/src/components/Select/docs/index.mdx
  lib/src/components/Select/docs/properties.json
  lib/src/components/Select/index.tsx
  lib/src/components/Select/multipleSelections.tsx
  lib/src/components/Select/select.module.scss
  lib/src/components/Select/tests/index.test.tsx
  lib/src/components/Select/tests/utils.test.ts
  lib/src/components/Select/types.ts
  lib/src/components/Select/utils.ts
  lib/src/components/Tabs/components/TabList/index.tsx
  lib/src/components/Tabs/docs/properties.json
  lib/src/components/Toggle/docs/properties.json
  lib/src/components/Tooltip/docs/properties.json
  lib/src/constants/field-icon-size.ts
  lib/src/types.ts
  lib/src/utils/create-event.ts
  lib/src/utils/text-ellipsis.scss
  lib/src/utils/useForkRef.ts
  stylelint.config.mjs
  website/build-app/examples.js
Labels: changes-requested, to-review

#2889 ci: migration script for Box and replace on website
  eslint-suppressions.json
  lib/src/components/CloseButton/docs/properties.json
  package.json
  scripts/upgrade-v8.js
  scripts/upgrade-v9.mjs
  website/app/blog/page.tsx
  website/app/components/page.tsx
  website/app/layout.tsx
  website/app/page.tsx
  website/build-app/components/Colors/index.tsx
  website/build-app/components/Footer/index.tsx
  website/build-app/components/Header/NavBar.tsx
  website/build-app/components/Header/index.tsx
  website/build-app/components/Homepage/Components.tsx
  website/build-app/components/Homepage/Expectations.tsx
  website/build-app/components/Homepage/Stats.tsx
  website/build-app/components/IconsList/index.tsx
  website/build-app/components/Mdx/Code.tsx
  website/build-app/components/Mdx/Div.tsx
  website/build-app/components/Mdx/Headings.tsx
  website/build-app/components/Mdx/Highlight.tsx
  website/build-app/components/Mdx/Image.tsx
  website/build-app/components/Mdx/Playground.tsx
  website/build-app/components/Mdx/index.tsx
  website/build-app/components/Props/index.tsx
  website/build-app/components/Section/index.tsx
  website/build-app/components/TableOfContent/index.tsx
  website/build-app/pages/foundations/theming/basics.mdx
  website/build-app/pages/foundations/upgrades/v9.mdx
Labels: approved

#2894 ci: add migration script to v9 for Grid component
  scripts/upgrade-v9.mjs
  website/app/components/page.tsx
  website/build-app/components/Colors/index.tsx
  website/build-app/components/Footer/index.tsx
  website/build-app/components/Theme/index.tsx
  website/build-app/layouts/Documentation/index.tsx
Labels: approved

#2865 chore: migrate Toast
  lib/package.json
  lib/src/components/DropdownMenu/docs/properties.json
  lib/src/components/Toast/components/Growl.tsx
  lib/src/components/Toast/components/Snackbar.tsx
  lib/src/components/Toast/docs/examples/custom-close.tsx
  lib/src/components/Toast/docs/examples/growl.tsx
  lib/src/components/Toast/docs/examples/overview.tsx
  lib/src/components/Toast/docs/examples/snackbar.tsx
  lib/src/components/Toast/docs/examples/toast.tsx
  lib/src/components/Toast/docs/examples/without-close.tsx
  lib/src/components/Toast/docs/index.mdx
  lib/src/components/Toast/docs/properties.json
  lib/src/components/Toast/index.test.tsx
  lib/src/components/Toast/index.tsx
  lib/src/components/Toast/toast.module.scss
  lib/src/components/Toast/types.ts
  website/app/global.css
  website/app/layout.tsx
  website/build-app/components/Header/index.tsx
  website/build-app/examples.js
  website/build-app/pages/foundations/upgrades/v9.mdx
  yarn.lock
Labels: approved

#2902 ci: fix migration script for Stack
  scripts/upgrade-v9.mjs
  website/app/blog/page.tsx
  website/build-app/components/Homepage/Components.tsx
  website/build-app/components/Mdx/Playground.tsx
Labels: approved

#2904 chore: migrate Card component
  lib/src/components/Badge/index.test.tsx
  lib/src/components/Badge/index.tsx
  lib/src/components/Card/Body.tsx
  lib/src/components/Card/Cover.tsx
  lib/src/components/Card/card.module.scss
  lib/src/components/Card/docs/examples/content.tsx
  lib/src/components/Card/docs/examples/overview.tsx
  lib/src/components/Card/docs/examples/picture.tsx
  lib/src/components/Card/docs/index.mdx
  lib/src/components/Card/docs/properties.json
  lib/src/components/Card/index.test.tsx
  lib/src/components/Card/index.tsx
  lib/src/components/Card/types.ts
  website/build-app/examples.js
  website/build-app/pages/foundations/upgrades/v9.mdx
Labels: approved

#2909 chore: improve textarea and input text type and style
  lib/src/components/InputText/docs/properties.json
  lib/src/components/InputText/index.tsx
  lib/src/components/InputText/input-text.module.scss
  lib/src/components/InputText/types.ts
  lib/src/components/PasswordInput/docs/properties.json
  lib/src/components/Textarea/docs/properties.json
  lib/src/components/Textarea/index.tsx
  lib/src/components/Textarea/textarea.module.scss
  lib/src/components/Textarea/types.ts
Labels: approved

#2892 chore migrate FileDrop + Files
  eslint-suppressions.json
  lib/package.json
  lib/src/components/FileDrop/components/FilePreview.tsx
  lib/src/components/FileDrop/components/Message.tsx
  lib/src/components/FileDrop/components/Preview.tsx
  lib/src/components/FileDrop/docs/examples/custom-filename.tsx
  lib/src/components/FileDrop/docs/examples/disabled.tsx
  lib/src/components/FileDrop/docs/examples/image.tsx
  lib/src/components/FileDrop/docs/examples/no-type.tsx
  lib/src/components/FileDrop/docs/examples/others.tsx
  lib/src/components/FileDrop/docs/examples/overview.tsx
  lib/src/components/FileDrop/docs/examples/preview.tsx
  lib/src/components/FileDrop/docs/examples/wordings.tsx
  lib/src/components/FileDrop/docs/index.mdx
  lib/src/components/FileDrop/docs/properties.json
  lib/src/components/FileDrop/filedrop.module.scss
  lib/src/components/FileDrop/index.tsx
  lib/src/components/FileDrop/types.ts
  lib/src/components/FileDrop/utils.ts
  lib/src/components/Files/index.test.ts
  lib/src/components/Files/index.ts
  lib/src/components/Files/types.ts
  lib/src/utils/index.ts
  lib/src/utils/ts-utils.ts
  website/app/global.css
  website/build-app/examples.js
  yarn.lock
Labels: approved

#2914 fix(imports): fix theme utils import paths
  lib/src/components/Drawer/AssetDrawer/asset-drawer.module.scss
  lib/src/components/Drawer/drawer.module.scss
  lib/src/components/Swiper/swiper.module.scss
Labels: approved

#2886 chore: migrate FileUpload & Files
  lib/src/components/FileDrop/types.ts
  lib/src/components/FileUpload/docs/examples/customize-button.tsx
  lib/src/components/FileUpload/docs/examples/customize-preview-2.tsx
  lib/src/components/FileUpload/docs/examples/customize-preview.tsx
  lib/src/components/FileUpload/docs/examples/disabled.tsx
  lib/src/components/FileUpload/docs/examples/multiple.tsx
  lib/src/components/FileUpload/docs/examples/overview.tsx
  lib/src/components/FileUpload/docs/examples/preview.tsx
  lib/src/components/FileUpload/docs/index.mdx
  lib/src/components/FileUpload/docs/properties.json
  lib/src/components/FileUpload/file-upload.module.scss
  lib/src/components/FileUpload/index.tsx
  lib/src/components/FileUpload/types.ts
  lib/src/components/Files/index.ts
  lib/src/components/Files/tests/index.test.ts
  lib/src/components/Files/types.ts
  website/build-app/components/Mdx/Playground.tsx
  website/build-app/examples.js
  website/build-app/pages/foundations/upgrades/v9.mdx
Labels: to-review

#2915 chore: use component based css instead of tailwind classes
  lib/src/components/Modal/Assets/AssetTitle.tsx
  lib/src/components/Modal/Assets/assets.module.scss
  lib/src/components/Modal/components/Footer.tsx
  lib/src/components/Modal/components/Header.tsx
  lib/src/components/Modal/modal.module.scss
  lib/src/components/Popover/docs/properties.json
Labels: approved

#2927 Chore: use breakpoint utils for breakpoint declarations
  lib/src/components/Modal/Assets/assets.module.scss
Labels: approved

#2926 Chore: migrate Search component to tailwind [WUI-172]
  lib/src/components/Search/docs/examples/option-groups.tsx
  lib/src/components/Search/docs/examples/overview.tsx
  lib/src/components/Search/docs/index.mdx
  lib/src/components/Search/docs/properties.json
  lib/src/components/Search/index.test.tsx
  lib/src/components/Search/index.tsx
  lib/src/components/Search/search.module.scss
  lib/src/components/Search/types.ts
  lib/src/components/Select/docs/properties.json
  lib/src/components/Select/index.tsx
  lib/src/components/Select/select.module.scss
  lib/src/utils/throttle.ts
  website/build-app/examples.js
Labels: to-review
